-- 표 생성 전 기존 생성된 표 삭제
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE REPORT CASCADE CONSTRAINTS;
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP TABLE TB_COMMENT CASCADE CONSTRAINTS;
DROP TABLE GUIDE_BOARD CASCADE CONSTRAINTS;
DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE CHATTING_ROOM CASCADE CONSTRAINTS;
DROP TABLE ROUTE_BOARD CASCADE CONSTRAINTS;
DROP TABLE ROUTE CASCADE CONSTRAINTS;
DROP TABLE PLACE CASCADE CONSTRAINTS;
DROP TABLE LIKE_COUNT CASCADE CONSTRAINTS;

-- 시퀀스 생성 전 기존 생성된 시퀀스 삭제
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE SEQ_ROUTE_BOARD;
DROP SEQUENCE SEQ_ROUTE;
DROP SEQUENCE SEQ_PLACE;
DROP SEQUENCE SEQ_CHATTING_ROOM;
DROP SEQUENCE SEQ_CHAT_MESSAGE;
DROP SEQUENCE SEQ_GUIDE_BOARD;
DROP SEQUENCE SEQ_COMMENT;

-- 표 생성
CREATE TABLE MEMBER (
	MEM_ID	            VARCHAR2(255),
	MEM_NAME           VARCHAR2(255) NOT NULL,
	MEM_TYPE           VARCHAR2(255) DEFAULT 'USER' NOT NULL,
	MEM_PW             VARCHAR2(500),
	MEM_NICKNM         VARCHAR2(50) NOT NULL,
	MEM_JOIN_DATE	    DATE DEFAULT SYSDATE,
	MEM_PHONE	        VARCHAR2(30),
	MEM_BIRTH	        DATE,
	MEM_SOCIAL	        VARCHAR2(100),
	MEM_STATUS	        VARCHAR(255) NOT NULL,   -- 사용자의 상태를 4가지로 구분. '정상 : ACTIVE' , '정지 : BLOCKED' , '휴면 : INACTIVE' , '탈퇴 : LEFT'
	MEM_LOGIN_LOG	    DATE,
	MEM_LOGOUT_LOG	    DATE,
	MEM_STATUS_DATE	DATE,
	MEM_PW_UPDATE	    DATE,
    CONSTRAINT PK_MEM_ID PRIMARY KEY (MEM_ID)
    , CONSTRAINT CHK_MEM_TYPE CHECK (MEM_TYPE IN ('USER', 'ADMIN'))
    , CONSTRAINT UQ_MEM_NICKNM UNIQUE (MEM_NICKNM)
    , CONSTRAINT CHK_MEM_STATUS CHECK (MEM_STATUS IN ('ACTIVE', 'BLOCKED', 'INACTIVE', 'LEFT'))
);

CREATE TABLE NOTICE (
	NOTICE_ID	    VARCHAR2(255),
	TITLE	        VARCHAR2(500) NOT NULL,
	CONTENT	    CLOB NOT NULL,
	ADMIN_ID	    VARCHAR2(255) NOT NULL,
	CREATED_AT	    DATE DEFAULT SYSDATE,
	UPDATED_AT	    DATE,
	UPDATE_CHECK	CHAR(1) DEFAULT 'N',
	DELETED_AT	    DATE,
	DELETE_CHECK	CHAR(1) DEFAULT 'N',
	OFILE1	        VARCHAR2(500),
	OFILE2	        VARCHAR2(500),
	OFILE3	        VARCHAR2(500),
    RFILE1	        VARCHAR2(500),
    RFILE2	        VARCHAR2(500),
    RFILE3	        VARCHAR2(500),
    CONSTRAINT PK_NOTICE_ID PRIMARY KEY (NOTICE_ID)
    , CONSTRAINT CHK_UPDATE_CHECK CHECK (UPDATE_CHECK IN ('Y', 'N'))
    , CONSTRAINT CHK_DELETE_CHECK CHECK (DELETE_CHECK IN ('Y', 'N'))
);

CREATE TABLE QNA (
	QNA_ID	        VARCHAR2(255),
	TITLE	        VARCHAR2(500) NOT NULL,
	USER_CONTENT	CLOB NOT NULL,
	USER_ID	        VARCHAR2(255) NOT NULL,
	Q_CREATED_AT	DATE DEFAULT SYSDATE,
	Q_UPDATED_AT	DATE,
	ADMIN_ID	    VARCHAR2(255),
	IS_ACCEPT	    CHAR(1) DEFAULT 'N',
	ADMIN_CONTENT	CLOB,
	A_CREATED_AT	DATE	DEFAULT SYSDATE,
    IS_SECRET       CHAR(1) DEFAULT 'Y',
    DELETE_AT       DATE DEFAULT SYSDATE,
    DELETE_CHECK    CHAR(1) DEFAULT 'N',
	OFILE1	        VARCHAR2(500),
	OFILE2	        VARCHAR2(500),
	OFILE3	        VARCHAR2(500),
	OFILE4	        VARCHAR2(500),
	OFILE5	        VARCHAR2(500),
    RFILE1	        VARCHAR2(500),
    RFILE2	        VARCHAR2(500),
    RFILE3	        VARCHAR2(500),
    RFILE4	        VARCHAR2(500),
    RFILE5	        VARCHAR2(500),
    CONSTRAINT PK_QNA_ID PRIMARY KEY (QNA_ID)
    , CONSTRAINT FK_QNA_USERID FOREIGN KEY (USER_ID) REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE
    , CONSTRAINT FK_QNA_ADMINID FOREIGN KEY (ADMIN_ID) REFERENCES MEMBER(MEM_ID)
    , CONSTRAINT CHK_IS_ACCEPT CHECK (IS_ACCEPT IN ('Y', 'N'))
);

CREATE TABLE REPORT (
	REPORT_ID	        VARCHAR2(255),
	POST_ID	            VARCHAR2(255) NOT NULL,
	REPORT_USER_ID	    VARCHAR2(255) NOT NULL,
	REPORTING_REASON	VARCHAR2(255),
	DETAIL	            VARCHAR2(255),
	REPORT_DATE	        DATE DEFAULT SYSDATE,
	CHECKED_ADMIN	    CHAR(1),
	CHECKED_ADMIN_ID	VARCHAR2(255) NOT NULL,
	CHECKED_ASSIGNED	CHAR(1),
	ASSIGNED_ADMIN_ID	VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_REPORT_ID PRIMARY KEY (REPORT_ID)
    , CONSTRAINT FK_REPORT_USER_ID FOREIGN KEY (REPORT_USER_ID) REFERENCES MEMBER(MEM_ID) ON DELETE SET NULL
    , CONSTRAINT CHK_CHECKED_ADMIN CHECK (CHECKED_ADMIN IN ('Y', 'N'))
    , CONSTRAINT FK_CHECKED_ADMIN_ID FOREIGN KEY (CHECKED_ADMIN_ID) REFERENCES MEMBER(MEM_ID)
    , CONSTRAINT CHK_CHECKED_ASSIGNED CHECK (CHECKED_ASSIGNED IN ('Y', 'N'))
    , CONSTRAINT FK_ASSIGNED_ADMIN_ID FOREIGN KEY (ASSIGNED_ADMIN_ID) REFERENCES MEMBER(MEM_ID)
);

CREATE TABLE TB_COMMENT (
	COMMENT_ID	VARCHAR2(255),
	USER_ID	    VARCHAR2(255) NOT NULL,
	POST_ID	    VARCHAR2(255) NOT NULL,
	CONTENT	CLOB NOT NULL,
	CREATED_AT	DATE DEFAULT SYSDATE,
	UPDATED_AT	DATE,
    CONSTRAINT PK_COMMENT_ID PRIMARY KEY (COMMENT_ID)
    , CONSTRAINT FK_COMMENT_USERID FOREIGN KEY (USER_ID) REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE
);

CREATE TABLE ROUTE_BOARD (
	ROUTE_BOARD_ID VARCHAR2(255),
	USER_ID	        VARCHAR2(255) NOT NULL,
	TITLE	        VARCHAR2(500) NOT NULL,
	CONTENT	    CLOB NOT NULL,
	TRANSPORT	    VARCHAR2(20),
	CREATED_AT	    DATE DEFAULT SYSDATE,
	UPDATED_AT	    DATE,
	LIKE_COUNT	    NUMBER DEFAULT 0,
	TOTAL_DURATION	NUMBER	,
	ROUTE_NAME	    VARCHAR2(300),
	OFILE1	        VARCHAR2(500),
	OFILE2	        VARCHAR2(500),
	OFILE3	        VARCHAR2(500),
	OFILE4	        VARCHAR2(500),
	OFILE5	        VARCHAR2(500),
	RFILE1	        VARCHAR2(500),
	RFILE2	        VARCHAR2(500),
	RFILE3	        VARCHAR2(500),
	RFILE4	        VARCHAR2(500),
	RFILE5	        VARCHAR2(500),
    CONSTRAINT PK_ROUTE_BOARD_ID PRIMARY KEY (ROUTE_BOARD_ID)
    , CONSTRAINT FK_ROUTE_BOARD_USERID FOREIGN KEY (USER_ID) REFERENCES MEMBER(MEM_ID) ON DELETE SET NULL
);

CREATE TABLE PLACE (
	PLACE_ID	        VARCHAR2(255),
	PLACE_NAME	    VARCHAR2(255) NOT NULL,
	ADDRESS 	    VARCHAR2(255),
	LATITUDE	        NUMBER,
	LONGITUDE	    NUMBER,
    CONSTRAINT PK_PLACE_ID PRIMARY KEY (PLACE_ID)
);

CREATE TABLE ROUTE (
	ROUTE_ID	            VARCHAR2(100),
	ROUTE_BOARD_ID	        VARCHAR2(255) NOT NULL,
	ROUTE_PLACE_ID	        VARCHAR2(255) NOT NULL,
	ROUTE_PLACE_ORDER_NO	NUMBER DEFAULT 0,
    CONSTRAINT PK_ROUTE_ID PRIMARY KEY (ROUTE_ID)
    , CONSTRAINT FK_ROUTE_BOARD_ID FOREIGN KEY (ROUTE_BOARD_ID) REFERENCES ROUTE_BOARD(ROUTE_BOARD_ID)
    , CONSTRAINT FK_ROUTE_PLACE_ID FOREIGN KEY (ROUTE_PLACE_ID) REFERENCES PLACE(PLACE_ID)
);

CREATE TABLE GUIDE_BOARD (
	POST_ID	VARCHAR2(255),
	TITLE	VARCHAR2(500) NOT NULL,
	CONTENT CLOB NOT NULL,
	LOCATION VARCHAR2(500) NOT NULL,
	CREATED_AT	DATE DEFAULT SYSDATE,
	UPDATED_AT	DATE,
	USER_ID	VARCHAR2(255) NOT NULL,
	LIKE_COUNT	NUMBER DEFAULT 0,
	OFILE1	VARCHAR2(500),
	OFILE2	VARCHAR2(500),
	OFILE3	VARCHAR2(500),
	OFILE4	VARCHAR2(500),
	OFILE5	VARCHAR2(500),
	RFILE1	VARCHAR2(500),
	RFILE2	VARCHAR2(500),
	RFILE3	VARCHAR2(500),
	RFILE4	VARCHAR2(500),
	RFILE5	VARCHAR2(500),
    CONSTRAINT PK_GUIDE_BOARD_ID PRIMARY KEY (POST_ID)
    , CONSTRAINT FK_GUIDE_BOARD_USERID FOREIGN KEY (USER_ID) REFERENCES MEMBER(MEM_ID) ON DELETE SET NULL
);

CREATE TABLE CHATTING_ROOM (
	CHATTING_NO	    VARCHAR2(255),
	CH_CREATE_DATE	DATE DEFAULT SYSDATE,
	GUIDE_ID	        VARCHAR2(255)		NOT NULL,
	USER_ID	        VARCHAR2(255)		NOT NULL,
    CONSTRAINT PK_CHATTING_NO PRIMARY KEY (CHATTING_NO)
    , CONSTRAINT FK_CHAT_GUIDEID FOREIGN KEY (GUIDE_ID) REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE
    , CONSTRAINT FK_CHAT_USERID FOREIGN KEY (USER_ID) REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE
);

CREATE TABLE CHAT_MESSAGE (
	MESSAGE_NO	        VARCHAR2(255),
	MESSAGE_CONTENT	CLOB NOT NULL,
	READ_FL	            CHAR(1) NOT NULL,
	SEND_TIME	        TIMESTAMP NOT NULL,
	MEM_ID	            VARCHAR2(255) NOT NULL,
	CHATTING_NO	        VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_MESSAGE_NO PRIMARY KEY (MESSAGE_NO)
    , CONSTRAINT FK_CHAT_MEM_ID FOREIGN KEY (MEM_ID) REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE
    , CONSTRAINT FK_CHATTING_NO FOREIGN KEY (CHATTING_NO) REFERENCES CHATTING_ROOM(CHATTING_NO)
    , CONSTRAINT CHK_READ_FL CHECK (READ_FL IN ('Y', 'N'))
);

CREATE TABLE LIKE_COUNT (
    USER_ID     VARCHAR2(255),
    POST_ID     VARCHAR2(255),
    CONSTRAINT PK_LIKE_COUNT PRIMARY KEY (USER_ID, POST_ID)
    , CONSTRAINT FK_LIKE_COUNT_USERID FOREIGN KEY (USER_ID) REFERENCES MEMBER (MEM_ID) ON DELETE SET NULL
);

-- comment 삽입
COMMENT ON COLUMN MEMBER.MEM_ID IS '사용자ID';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '사용자이름';
COMMENT ON COLUMN MEMBER.MEM_TYPE IS '사용자타입';
COMMENT ON COLUMN MEMBER.MEM_PW IS '사용자비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NICKNM IS '사용자닉네임';
COMMENT ON COLUMN MEMBER.MEM_JOIN_DATE IS '가입날짜';
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.MEM_BIRTH IS '생년월일';
COMMENT ON COLUMN MEMBER.MEM_SOCIAL IS '소셜구분';
COMMENT ON COLUMN MEMBER.MEM_STATUS IS '사용자상태';
COMMENT ON COLUMN MEMBER.MEM_LOGIN_LOG IS '로그인기록';
COMMENT ON COLUMN MEMBER.MEM_LOGOUT_LOG IS '로그아웃기록';
COMMENT ON COLUMN MEMBER.MEM_STATUS_DATE IS '사용자상태적용날짜';
COMMENT ON COLUMN MEMBER.MEM_PW_UPDATE IS '비밀번호수정날짜';

COMMENT ON COLUMN NOTICE.NOTICE_ID IS '공지식별코드';
COMMENT ON COLUMN NOTICE.TITLE IS '공지제목';
COMMENT ON COLUMN NOTICE.CONTENT IS '공지내용';
COMMENT ON COLUMN NOTICE.ADMIN_ID IS '작성한관리자ID';
COMMENT ON COLUMN NOTICE.CREATED_AT IS '공지작성일자';
COMMENT ON COLUMN NOTICE.UPDATED_AT IS '공지수정일자';
COMMENT ON COLUMN NOTICE.UPDATE_CHECK IS '공지수정여부';
COMMENT ON COLUMN NOTICE.DELETED_AT IS '공지삭제일자';
COMMENT ON COLUMN NOTICE.DELETE_CHECK IS '공지삭제여부';
COMMENT ON COLUMN NOTICE.OFILE1 IS '기존첨부파일1';
COMMENT ON COLUMN NOTICE.OFILE2 IS '기존첨부파일2';
COMMENT ON COLUMN NOTICE.OFiLE3 IS '기존첨부파일3';
COMMENT ON COLUMN NOTICE.RFiLE1 IS '수정첨부파일1';
COMMENT ON COLUMN NOTICE.RFiLE2 IS '수정첨부파일2';
COMMENT ON COLUMN NOTICE.RFiLE3 IS '수정첨부파일3';


COMMENT ON COLUMN QNA.QNA_ID IS '질문글식별코드';
COMMENT ON COLUMN QNA.TITLE IS '질문제목';
COMMENT ON COLUMN QNA.USER_CONTENT IS '질문내용';
COMMENT ON COLUMN QNA.USER_ID IS '질문작성자ID';
COMMENT ON COLUMN QNA.Q_CREATED_AT IS '질문작성일자';
COMMENT ON COLUMN QNA.Q_UPDATED_AT IS '질문수정일자';
COMMENT ON COLUMN QNA.ADMIN_ID IS '답변관리자ID';
COMMENT ON COLUMN QNA.IS_ACCEPT IS '답변여부';
COMMENT ON COLUMN QNA.ADMIN_CONTENT IS '답변내용';
COMMENT ON COLUMN QNA.A_CREATED_AT IS '답변작성일자';
COMMENT ON COLUMN QNA.IS_SECRET IS '질문공개여부';
COMMENT ON COLUMN QNA.OFILE1 IS '기존첨부파일1';
COMMENT ON COLUMN QNA.OFILE2 IS '기존첨부파일2';
COMMENT ON COLUMN QNA.OFILE3 IS '기존첨부파일3';
COMMENT ON COLUMN QNA.OFILE4 IS '기존첨부파일4';
COMMENT ON COLUMN QNA.OFILE5 IS '기존첨부파일5';
COMMENT ON COLUMN QNA.RFILE1 IS '수정첨부파일1';
COMMENT ON COLUMN QNA.RFILE2 IS '수정첨부파일2';
COMMENT ON COLUMN QNA.RFILE3 IS '수정첨부파일3';
COMMENT ON COLUMN QNA.RFILE4 IS '수정첨부파일4';
COMMENT ON COLUMN QNA.RFILE5 IS '수정첨부파일5';

COMMENT ON COLUMN GUIDE_BOARD.POST_ID IS '게시글식별코드';
COMMENT ON COLUMN GUIDE_BOARD.TITLE IS '가이드글제목';
COMMENT ON COLUMN GUIDE_BOARD.CONTENT IS '가이드글내용';
COMMENT ON COLUMN GUIDE_BOARD.LOCATION IS '지역';
COMMENT ON COLUMN GUIDE_BOARD.CREATED_AT IS '가이드글작성일자';
COMMENT ON COLUMN GUIDE_BOARD.UPDATED_AT IS '가이드글수정일자';
COMMENT ON COLUMN GUIDE_BOARD.USER_ID IS '가이드ID';
COMMENT ON COLUMN GUIDE_BOARD.LIKE_COUNT IS '게시글 추천수';
COMMENT ON COLUMN GUIDE_BOARD.OFILE1 IS '기존첨부파일1';
COMMENT ON COLUMN GUIDE_BOARD.OFILE2 IS '기존첨부파일2';
COMMENT ON COLUMN GUIDE_BOARD.OFILE3 IS '기존첨부파일3';
COMMENT ON COLUMN GUIDE_BOARD.OFILE4 IS '기존첨부파일4';
COMMENT ON COLUMN GUIDE_BOARD.OFILE5 IS '기존첨부파일5';
COMMENT ON COLUMN GUIDE_BOARD.RFILE1 IS '수정첨부파일1';
COMMENT ON COLUMN GUIDE_BOARD.RFILE2 IS '수정첨부파일2';
COMMENT ON COLUMN GUIDE_BOARD.RFILE3 IS '수정첨부파일3';
COMMENT ON COLUMN GUIDE_BOARD.RFILE4 IS '수정첨부파일4';
COMMENT ON COLUMN GUIDE_BOARD.RFILE5 IS '수정첨부파일5';

COMMENT ON COLUMN TB_COMMENT.COMMENT_ID IS '댓글식별코드';
COMMENT ON COLUMN TB_COMMENT.USER_ID IS '댓글작성자ID';
COMMENT ON COLUMN TB_COMMENT.POST_ID IS '게시글ID';
COMMENT ON COLUMN TB_COMMENT.CONTENT IS '댓글내용';
COMMENT ON COLUMN TB_COMMENT.CREATED_AT IS '댓글작성일자';
COMMENT ON COLUMN TB_COMMENT.UPDATED_AT IS '댓글수정일자';

COMMENT ON COLUMN ROUTE_BOARD.ROUTE_BOARD_ID IS '경로추천게시글식별코드';
COMMENT ON COLUMN ROUTE_BOARD.USER_ID IS '경로추천글작성자ID';
COMMENT ON COLUMN ROUTE_BOARD.TITLE IS '경로추천글제목';
COMMENT ON COLUMN ROUTE_BOARD.CONTENT IS '경로추천내용';
COMMENT ON COLUMN ROUTE_BOARD.TRANSPORT IS '교통수단';
COMMENT ON COLUMN ROUTE_BOARD.CREATED_AT IS '글작성일자';
COMMENT ON COLUMN ROUTE_BOARD.UPDATED_AT IS '글수정일자';
COMMENT ON COLUMN ROUTE_BOARD.LIKE_COUNT IS '게시글추천수';
COMMENT ON COLUMN ROUTE_BOARD.TOTAL_DURATION IS '추천한경로 총 소요시간';
COMMENT ON COLUMN ROUTE_BOARD.ROUTE_NAME IS '추천경로이름';
COMMENT ON COLUMN ROUTE_BOARD.OFILE1 IS '기존첨부파일1';
COMMENT ON COLUMN ROUTE_BOARD.OFILE2 IS '기존첨부파일2';
COMMENT ON COLUMN ROUTE_BOARD.OFILE3 IS '기존첨부파일3';
COMMENT ON COLUMN ROUTE_BOARD.OFILE4 IS '기존첨부파일4';
COMMENT ON COLUMN ROUTE_BOARD.OFILE5 IS '기존첨부파일5';
COMMENT ON COLUMN ROUTE_BOARD.RFILE1 IS '수정첨부파일1';
COMMENT ON COLUMN ROUTE_BOARD.RFILE2 IS '수정첨부파일2';
COMMENT ON COLUMN ROUTE_BOARD.RFILE3 IS '수정첨부파일3';
COMMENT ON COLUMN ROUTE_BOARD.RFILE4 IS '수정첨부파일4';
COMMENT ON COLUMN ROUTE_BOARD.RFILE5 IS '수정첨부파일5';

COMMENT ON COLUMN PLACE.PLACE_ID IS '장소식별코드';
COMMENT ON COLUMN PLACE.PLACE_NAME IS '장소이름';
COMMENT ON COLUMN PLACE.ADDRESS IS '주소';
COMMENT ON COLUMN PLACE.LATITUDE IS '위도';
COMMENT ON COLUMN PLACE.LONGITUDE IS '경도';

COMMENT ON COLUMN ROUTE.ROUTE_ID IS '경로식별코드';
COMMENT ON COLUMN ROUTE.ROUTE_BOARD_ID IS '게시글식별코드';
COMMENT ON COLUMN ROUTE.ROUTE_PLACE_ID IS '경유지식별코드';
COMMENT ON COLUMN ROUTE.ROUTE_PLACE_ORDER_NO IS '경유지순번';

COMMENT ON COLUMN GUIDE_BOARD.POST_ID IS '게시글식별코드';
COMMENT ON COLUMN GUIDE_BOARD.TITLE IS '가이드글제목';
COMMENT ON COLUMN GUIDE_BOARD.CONTENT IS '가이드글내용';
COMMENT ON COLUMN GUIDE_BOARD.LOCATION IS '지역';
COMMENT ON COLUMN GUIDE_BOARD.CREATED_AT IS '가이드글작성일자';
COMMENT ON COLUMN GUIDE_BOARD.UPDATED_AT IS '가이드글수정일자';
COMMENT ON COLUMN GUIDE_BOARD.USER_ID IS '가이드ID';
COMMENT ON COLUMN GUIDE_BOARD.LIKE_COUNT IS '게시글 추천수';
COMMENT ON COLUMN GUIDE_BOARD.OFILE1 IS '기존첨부파일1';
COMMENT ON COLUMN GUIDE_BOARD.OFILE2 IS '기존첨부파일2';
COMMENT ON COLUMN GUIDE_BOARD.OFILE3 IS '기존첨부파일3';
COMMENT ON COLUMN GUIDE_BOARD.OFILE4 IS '기존첨부파일4';
COMMENT ON COLUMN GUIDE_BOARD.OFILE5 IS '기존첨부파일5';
COMMENT ON COLUMN GUIDE_BOARD.RFILE1 IS '수정첨부파일1';
COMMENT ON COLUMN GUIDE_BOARD.RFILE2 IS '수정첨부파일2';
COMMENT ON COLUMN GUIDE_BOARD.RFILE3 IS '수정첨부파일3';
COMMENT ON COLUMN GUIDE_BOARD.RFILE4 IS '수정첨부파일4';
COMMENT ON COLUMN GUIDE_BOARD.RFILE5 IS '수정첨부파일5';

COMMENT ON COLUMN CHATTING_ROOM.CHATTING_NO IS '채팅방식별코드';
COMMENT ON COLUMN CHATTING_ROOM.CH_CREATE_DATE IS '채팅방생성일자';
COMMENT ON COLUMN CHATTING_ROOM.GUIDE_ID IS '채팅방개설자ID';
COMMENT ON COLUMN CHATTING_ROOM.USER_ID IS '채팅방참여자ID';

COMMENT ON COLUMN CHAT_MESSAGE.MESSAGE_NO IS '채팅내역식별코드';
COMMENT ON COLUMN CHAT_MESSAGE.MESSAGE_CONTENT IS '채팅내용';
COMMENT ON COLUMN CHAT_MESSAGE.READ_FL IS '읽음여부';
COMMENT ON COLUMN CHAT_MESSAGE.SEND_TIME IS '채팅보낸시간';
COMMENT ON COLUMN CHAT_MESSAGE.MEM_ID IS '채팅보낸사용자ID';
COMMENT ON COLUMN CHAT_MESSAGE.CHATTING_NO IS '채팅방식별코드';

COMMENT ON COLUMN LIKE_COUNT.USER_ID IS '추천자ID';
COMMENT ON COLUMN LIKE_COUNT.POST_ID IS '게시글 식별코드';

-- 식별코드를 위한 시퀀스 생성
-- 공지사항 식별코드 시퀀스
CREATE SEQUENCE SEQ_NOTICE
START WITH 100
NOCYCLE
NOCACHE;

-- 신고관리 식별코드 시퀀스
CREATE SEQUENCE SEQ_REPORT
NOCYCLE
NOCACHE;

-- QnA 식별코드 시퀀스
CREATE SEQUENCE SEQ_QNA
NOCYCLE
NOCACHE;

-- 경로추천게시판 식별코드 시퀀스
CREATE SEQUENCE SEQ_ROUTE_BOARD
NOCYCLE
NOCACHE;

-- 경로관리 식별코드 시퀀스
CREATE SEQUENCE SEQ_ROUTE
NOCYCLE
NOCACHE;

-- 장소관리 식별코드 시퀀스
CREATE SEQUENCE SEQ_PLACE
NOCYCLE
NOCACHE;

-- 채팅방 식별코드 시퀀스
CREATE SEQUENCE SEQ_CHATTING_ROOM
NOCYCLE
NOCACHE;

-- 채팅내역 식별코드 시퀀스
CREATE SEQUENCE SEQ_CHAT_MESSAGE
NOCYCLE
NOCACHE;

-- 가이드게시판 식별코드 시퀀스
CREATE SEQUENCE SEQ_GUIDE_BOARD
NOCYCLE
NOCACHE;

-- 댓글 식별코드 시퀀스
CREATE SEQUENCE SEQ_COMMENT
NOCYCLE
NOCACHE;

-- 관리자 아이디 생성
INSERT INTO MEMBER (MEM_ID, MEM_NAME, MEM_TYPE, MEM_PW, MEM_NICKNM, MEM_JOIN_DATE, MEM_STATUS)
VALUES ('ADMIN@synergysoft.co.kr', '관리자', 'ADMIN', '123456', 'ADMIN', SYSDATE, 'ACTIVE');
COMMIT;

-- 공지사항(notice) test data 추가
DELETE FROM NOTICE;
COMMIT;
INSERT INTO NOTICE VALUES ('notice_1','1.공지사항입니다.','공지사항 내용1','admin','2024-03-20',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_2','2.공지사항입니다.','공지사항 내용2','admin','2024-03-21',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_3','3.공지사항입니다.','공지사항 내용3','admin','2024-03-22',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_4','4.공지사항입니다.','공지사항 내용4','admin','2024-03-23',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_5','5.공지사항입니다.','공지사항 내용5','admin','2024-03-24',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_6','6.공지사항입니다.','공지사항 내용6','admin','2024-03-25',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_7','7.공지사항입니다.','공지사항 내용7','admin','2024-03-26',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_8','8.공지사항입니다.','공지사항 내용8','admin','2024-03-27',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_9','9.공지사항입니다.','공지사항 내용9','admin','2024-03-28',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_10','10.공지사항입니다.','공지사항 내용10','admin','2024-03-29',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_11','11.공지사항입니다.','공지사항 내용11','admin','2024-03-30',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_12','12.공지사항입니다.','공지사항 내용12','admin','2024-03-31',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_13','13.공지사항입니다.','공지사항 내용13','admin','2024-04-01',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_14','14.공지사항입니다.','공지사항 내용14','admin','2024-04-02',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_15','15.공지사항입니다.','공지사항 내용15','admin','2024-04-03',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_16','16.공지사항입니다.','공지사항 내용16','admin','2024-04-04',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_17','17.공지사항입니다.','공지사항 내용17','admin','2024-04-05',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_18','18.공지사항입니다.','공지사항 내용18','admin','2024-04-06',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_19','19.공지사항입니다.','공지사항 내용19','admin','2024-04-07',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_20','20.공지사항입니다.','공지사항 내용20','admin','2024-04-08',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_21','21.공지사항입니다.','공지사항 내용21','admin','2024-04-09',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_22','22.공지사항입니다.','공지사항 내용22','admin','2024-04-10',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_23','23.공지사항입니다.','공지사항 내용23','admin','2024-04-11',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_24','24.공지사항입니다.','공지사항 내용24','admin','2024-04-12',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_25','25.공지사항입니다.','공지사항 내용25','admin','2024-04-13',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_26','26.공지사항입니다.','공지사항 내용26','admin','2024-04-14',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_27','27.공지사항입니다.','공지사항 내용27','admin','2024-04-15',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_28','28.공지사항입니다.','공지사항 내용28','admin','2024-04-16',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_29','29.공지사항입니다.','공지사항 내용29','admin','2024-04-17',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_30','30.공지사항입니다.','공지사항 내용30','admin','2024-04-18',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_31','31.공지사항입니다.','공지사항 내용31','admin','2024-04-19',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_32','32.공지사항입니다.','공지사항 내용32','admin','2024-04-20',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_33','33.공지사항입니다.','공지사항 내용33','admin','2024-04-21',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_34','34.공지사항입니다.','공지사항 내용34','admin','2024-04-22',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_35','35.공지사항입니다.','공지사항 내용35','admin','2024-04-23',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_36','36.공지사항입니다.','공지사항 내용36','admin','2024-04-24',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_37','37.공지사항입니다.','공지사항 내용37','admin','2024-04-25',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_38','38.공지사항입니다.','공지사항 내용38','admin','2024-04-26',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_39','39.공지사항입니다.','공지사항 내용39','admin','2024-04-27',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_40','40.공지사항입니다.','공지사항 내용40','admin','2024-04-28',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_41','41.공지사항입니다.','공지사항 내용41','admin','2024-04-29',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_42','42.공지사항입니다.','공지사항 내용42','admin','2024-04-30',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_43','43.공지사항입니다.','공지사항 내용43','admin','2024-05-01',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_44','44.공지사항입니다.','공지사항 내용44','admin','2024-05-02',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_45','45.공지사항입니다.','공지사항 내용45','admin','2024-05-03',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_46','46.공지사항입니다.','공지사항 내용46','admin','2024-05-04',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_47','47.공지사항입니다.','공지사항 내용47','admin','2024-05-05',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_48','48.공지사항입니다.','공지사항 내용48','admin','2024-05-06',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_49','49.공지사항입니다.','공지사항 내용49','admin','2024-05-07',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_50','50.공지사항입니다.','공지사항 내용50','admin','2024-05-08',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_51','51.공지사항입니다.','공지사항 내용51','admin','2024-05-09',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_52','52.공지사항입니다.','공지사항 내용52','admin','2024-05-10',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_53','53.공지사항입니다.','공지사항 내용53','admin','2024-05-11',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_54','54.공지사항입니다.','공지사항 내용54','admin','2024-05-12',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_55','55.공지사항입니다.','공지사항 내용55','admin','2024-05-13',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_56','56.공지사항입니다.','공지사항 내용56','admin','2024-05-14',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_57','57.공지사항입니다.','공지사항 내용57','admin','2024-05-15',null,'N',null,'N',null,null,null,null,null,null);
INSERT INTO NOTICE VALUES ('notice_58','58.공지사항입니다.','공지사항 내용58','admin','2024-05-16',null,'N',null,'N',null,null,null,null,null,null);
commit;

-- 공지사항(notice) test data 추가

INSERT INTO guide_board (POST_ID, TITLE, CONTENT, LOCATION, CREATED_AT, UPDATED_AT, USER_ID, LIKE_COUNT)
VALUES ('001', '블로그 포스트1입니다.', '블로그에 들어가는 내용입니다. 확인해주세요1', '서울', TO_DATE('2022-11-22', 'YYYY-MM-DD'), TO_DATE('2023-12-01', 'YYYY-MM-DD'), 'user01', 71);

INSERT INTO guide_board (POST_ID, TITLE, CONTENT, LOCATION, CREATED_AT, UPDATED_AT, USER_ID, LIKE_COUNT)
VALUES ('002', '블로그 포스트2입니다.', '블로그에 들어가는 내용입니다. 확인해주세요2', '부산', TO_DATE('2022-12-30', 'YYYY-MM-DD'), TO_DATE('2023-12-02', 'YYYY-MM-DD'), 'user01', 72);


INSERT INTO guide_board (POST_ID, TITLE, CONTENT, LOCATION, CREATED_AT, UPDATED_AT, USER_ID, LIKE_COUNT)
VALUES ('003', '블로그 포스트3입니다.', '블로그에 들어가는 내용입니다. 확인해주세요3', '대전', TO_DATE('2022-10-03', 'YYYY-MM-DD'), TO_DATE('2023-12-03', 'YYYY-MM-DD'), 'user01', 73);

INSERT INTO guide_board (POST_ID, TITLE, CONTENT, LOCATION, CREATED_AT, UPDATED_AT, USER_ID, LIKE_COUNT)
VALUES ('004', '블로그 포스트4입니다.', '블로그에 들어가는 내용입니다. 확인해주세요4', '경주', TO_DATE('2022-09-23', 'YYYY-MM-DD'), TO_DATE('2023-12-04', 'YYYY-MM-DD'), 'user01', 5);

INSERT INTO guide_board (POST_ID, TITLE, CONTENT, LOCATION, CREATED_AT, UPDATED_AT, USER_ID, LIKE_COUNT)
VALUES ('005', '블로그 포스트5입니다.', '블로그에 들어가는 내용입니다. 확인해주세요5', '대전', TO_DATE('2022-12-31', 'YYYY-MM-DD'), TO_DATE('2023-12-05', 'YYYY-MM-DD'), 'user01', 79);

INSERT INTO guide_board (POST_ID, TITLE, CONTENT, LOCATION, CREATED_AT, UPDATED_AT, USER_ID, LIKE_COUNT)
VALUES ('006', '블로그 포스트6입니다.', '블로그에 들어가는 내용입니다. 확인해주세요6', '광주', TO_DATE('2022-10-13', 'YYYY-MM-DD'), TO_DATE('2023-12-06', 'YYYY-MM-DD'), 'user01', 77);

commit;


-- 기존백업테이블 삭제
DROP TABLE NOTICE_20240928;
-- 백업테이블 생성
CREATE TABLE NOTICE_20240928 AS SELECT * FROM NOTICE;
